### ISSUE TITLE
Publishing vendored cargo tarballs

### ISSUE THREAD

**Issue by dvc94ch** [alexcrichton/cargo-vendor#11]
This would be really nice for packaging cargo. I'm working on a different distro now and it's not easy to package cargo (150+ dependencies - we also run the test suites for most packages).

This would be related to `Task: Publish source tarballs of Cargo releases` [0] and the issue on the cargo issue tracker [1].

Are there plans to do this (soon)?

[0] https://internals.rust-lang.org/t/perfecting-rust-packaging-the-plan/2767
[1] https://github.com/rust-lang/cargo/issues/2107

**Comment by alexcrichton** [comment]
Currently we don't have plans on doing this, but if necessary it can be done! I've commented on the Cargo issue that we'll probably want to use this to vendor dependencies.

Is there something particularly actionable from this issue on this repo though? Or maybe it should be closed?

**Comment by dvc94ch** [comment]
Sounds good, thanks!
