### ISSUE TITLE
cargo install cargo-vendor fails with openssl error on Linux

### ISSUE THREAD

**Issue by staktrace** [alexcrichton/cargo-vendor#12]
Running `cargo install cargo-vendor` was working a week ago, but since then I had to reinstall my Linux machine, and for some reason it's failing now:

kats@kgupta-pc ~$ cargo install cargo-vendor
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: failed to compile `cargo-vendor v0.1.2`, intermediate artifacts can be found at `/tmp/cargo-install.ft8ioYIvQxvz`

Caused by:
  native library `openssl` is being linked to by more than one version of the same package, but it can only be linked once; try updating or pinning your dependencies to ensure that this package only shows up once

  openssl-sys v0.9.0
  openssl-sys v0.7.17

I seem to be able to install cargo-vendor fine on OS X, so it might just be a problem with my Linux setup - but I'm not sure what could be going wrong. Any suggestions welcome.

**Comment by alexcrichton** [comment]
I believe this should be fixed now, thanks for the report!

**Comment by staktrace** [comment]
Confirmed working now, thanks!
