### ISSUE TITLE
Error on backtrace dependency: No such file or directory for .gitmodules

### ISSUE THREAD

**Issue by mmstick** [alexcrichton/cargo-vendor#129]
Any idea what would cause this to happen?

```
error: failed to calculate checksum of: /<<PKGBUILDDIR>>/vendor/backtrace/.gitmodules

Caused by:
  No such file or directory (os error 2)
```

The file does exist, however:

```
# ls vendor/backtrace -a
.   appveyor.yml	  Cargo.toml  examples	   LICENSE-APACHE  README.md  tests
..  .cargo-checksum.json  ci	      .gitmodules  LICENSE-MIT	   src	      .travis.yml
```

**Comment by mmstick** [comment]
This seems to be an issue with something that `dpkg-buildpackage` is doing in a `schroot`. It may be stripping / modifying some files when it creates the source tarball, then extracts and builds from that tarball.

**Comment by alexcrichton** [comment]
Ah unfortunately I don't really know what's going on here to cause that error. Is there a way to reproduce perhaps?

**Comment by mmstick** [comment]
I seem to be able to work around the issue if I am to create a tarball for the vendored sources in advance, which preserves permissions. This way, `dpkg-buildpackage` won't end up tampering with any of the vendored sources when it goes to create the source tarball.
