### ISSUE TITLE
Copying of symlinks fails

### ISSUE THREAD

**Issue by joelgallant** [alexcrichton/cargo-vendor#143]
Fails [here](https://github.com/alexcrichton/cargo-vendor/blob/master/src/main.rs#L529) when a dependency contains a soft symlink that needs to be copied (`failed to copy /home/joel/.cargo/git/checkouts/foo/sha1/foo/bar to /home/joel/dev/baz/vendor/foo/bar`).

Where `foo/bar` is a symlink to another directory in the crate. I can replicate the same kinda thing with `cp foo/bar dest`, needs to be `cp --no-dereference foo/bar dest`. I don't know how to do the same thing with `fs::copy`, I haven't run in to that with std before. Would it need to check is_symlink and `std::os::unix::fs::symlink` manually?

**Comment by alexcrichton** [comment]
Ah yeah this is a case where `is_symlink` and such will need to be manually used, but seems reasonable to me!

**Comment by joelgallant** [comment]
Seems similar if not the same kind of error as https://github.com/rust-lang/cargo/issues/3896 - since fs::copy tries to follow the symlink

**Comment by alexcrichton** [comment]
This crate is now included natively in Cargo as of https://github.com/rust-lang/cargo/pull/6869 and today's nightly Rust. I'm closing all issues in this repository before I archive the repository, but if you're still interested in seeing this issue fixed then please feel free to file an issue with [Cargo itself](https://github.com/rust-lang/cargo/issues/new)!
