### ISSUE TITLE
Fetch compiler-builtins for targets where it isn't already included by rustup

### ISSUE THREAD

**Issue by james-darkfox** [alexcrichton/cargo-vendor#177]
When doing any development using xargo or cargo-xbuild with a custom target, the compiler-builtins crate needs to be fetched. This used to just work. *shrug*

**Comment by alexcrichton** [comment]
This crate is now included natively in Cargo as of https://github.com/rust-lang/cargo/pull/6869 and today's nightly Rust. I'm closing all issues in this repository before I archive the repository, but if you're still interested in seeing this issue fixed then please feel free to file an issue with [Cargo itself](https://github.com/rust-lang/cargo/issues/new)!
