### ISSUE TITLE
".cargo-checksum.json" is not friendly to merge tools

### ISSUE THREAD

**Issue by upsuper** [alexcrichton/cargo-vendor#18]
The ".cargo-checksum.json" file generated by `cargo vendor` for each vendored crate is not very friendly to merge tools. It contains all data in one line, which makes  it hard to figure out the change for merge tools (and human who handles the conflict).

Cargo should probably pretty-print the json to that file, and keep each file in separate lines.

**Comment by alexcrichton** [comment]
Yeah it's true it's not very merge-friendly, but why would we want it to be? It's just a blob of opaque json and the files already have good diffs associated with them?

**Comment by upsuper** [comment]
Hmmm, yeah, you're right. It doesn't seem to be necessary. I hope merge tools can treat each vendored crate as a whole rather than trying to merge every single file :/ But that's not related to cargo anyway.
