### ISSUE TITLE
cargo-vendor as a standalone

### ISSUE THREAD

**Issue by pylaligand** [alexcrichton/cargo-vendor#19]
Can cargo-vendor be used on it own without cargo? I tried to `cargo build` it and then run target/debug/cargo-vendor but am getting errors:
```
$ target/debug/cargo-vendor -h
Hello!
error: Invalid arguments.

Usage:
    cargo vendor [options] [<path>]
```

**Comment by pylaligand** [comment]
It looks like the right invocation is:
```
target/debug/cargo-vendor vendor -h
```

**Comment by alexcrichton** [comment]
Ah yeah, that does the trick!
