### ISSUE TITLE
Can't vendor two compatible crate versions from two projects

### ISSUE THREAD

**Issue by alexcrichton** [alexcrichton/cargo-vendor#20]
More info at -- https://bugzilla.mozilla.org/show_bug.cgi?id=1336528#c3

**Comment by LegNeato** [comment]
Note that using `-x` is of no help, even though setting the option you would expect `cargo vendor` to save both versions and prefer the specific version first before falling back to the most recent version.

The reason why this isn't a showstopper for Mozilla is that they delete the directory every time:

https://bugzilla.mozilla.org/show_bug.cgi?id=1336528#c5

Which apparently works around this bug:

https://bugzilla.mozilla.org/show_bug.cgi?id=1336528#c4

(though I can't get the workaround to work, I am stuck)
