### ISSUE TITLE
Vendoring from a git repository should include files as if they were published

### ISSUE THREAD

**Issue by glandium** [alexcrichton/cargo-vendor#203]
When we vendor forked versions of crates from git repositories in Firefox, cargo vendor adds plenty of files that wouldn't be there if the crate had been published on crates.io, like CI files, .gitignore, etc. Even Cargo.toml is normalized, and this makes vendoring more noisy than necessary.

See e.g.
https://phabricator.services.mozilla.com/D18767
https://phabricator.services.mozilla.com/D20289

**Comment by alexcrichton** [comment]
This crate is now included natively in Cargo as of https://github.com/rust-lang/cargo/pull/6869 and today's nightly Rust. I'm closing all issues in this repository before I archive the repository, but if you're still interested in seeing this issue fixed then please feel free to file an issue with [Cargo itself](https://github.com/rust-lang/cargo/issues/new)!
