### ISSUE TITLE
.cargo-checksum.json stores backslash in filename on Windows

### ISSUE THREAD

**Issue by upsuper** [alexcrichton/cargo-vendor#22]
On Windows the content of ".cargo-checksum.json" looks like:
```json
{"files":{
  ".cargo-ok":"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
  ".gitignore":"12cc0f91b51fedf41ae1670d1624ee1d78a284bdb101645b60a06a12de16c069",
  ".travis.yml":"6b96b2c6bfd7e1acef4b825a2813fc4277859eb9400a16800db8835c25e4087d",
  "Cargo.toml":"b3ccbfb0273b9c3eaaa9bc30eba9c0e1ee8079d672dd367d8bd7b7049fe24de7",
  "README.md":"9f048d969f9f8333cdcdb892744cd0816e4f2922c8817fa5e9e07f9472fe1050",
  "src\\app_unit.rs":"4927de20034ba6fc6454caa3e389dc2504f1b0bcad0a2427b52bef2f87b8f69c",
  "src\\lib.rs":"2df7d863c47d8b22f9af66caeafa87e6a206ee713a8aeaa55c5a80a42a92513b"
},"package":"5a0c3b5be4ed53affe3e1a162b2e7ef9979bcaac80daa9026e9d7988c41e0e83"}
```
that the paths use backslash, rather than slash.

It is undesired because we check in those files in Gecko's repo, and don't want the content to change depending on what platform `cargo vendor` is executed on.

**Comment by alexcrichton** [comment]
Yeah I ran into this recently with rust-lang/rust as well, I think I'll just fix this to always use `/`

**Comment by alexcrichton** [comment]
Fixed in https://github.com/alexcrichton/cargo-vendor/commit/05950d961eaa0a82cf15f273c1b37c0eda52309b

**Comment by upsuper** [comment]
@alexcrichton could you publish a new version for this?

**Comment by alexcrichton** [comment]
@upsuper certainly!
