### ISSUE TITLE
Support for path dependencies

### ISSUE THREAD

**Issue by bbigras** [alexcrichton/cargo-vendor#25]
I have some dependencies like this:
```toml
mydep = { path = "/some/path" }
```

cargo-vendor doesn't seem to include them in the vendor directory. Normally it's not needed except when using Docker.

**Comment by alexcrichton** [comment]
Note that Cargo itself doesn't have support for this, so this would likely need to be implemented there first.

**Comment by bbigras** [comment]
cargo-vendor is nice with Docker to not have to re-download everything but we still need to recompile everything. If caching is the solution to that maybe I don't need support for path dependencies.

**Comment by alexcrichton** [comment]
Oh so typically path dependencies are idiomatically within the same "repository" or working-directory ish, when using path dependencies across the filesystem and/or other repos you'll typically want to use something like `[replace]` or git dependencies instead.

**Comment by XX** [comment]
What about support `path` now?

**Comment by autodidaddict** [comment]
Cargo supports path-relative dependencies, but cargo vendor doesn't @alexcrichton . This means I can't use a Dockerfile to create a docker image of a project I'm working on if that project isn't published in git or crates.io. There are hacky workarounds, but it would be great if vendor worked on paths.

**Comment by alexcrichton** [comment]
This crate is now included natively in Cargo as of https://github.com/rust-lang/cargo/pull/6869 and today's nightly Rust. I'm closing all issues in this repository before I archive the repository, but if you're still interested in seeing this issue fixed then please feel free to file an issue with [Cargo itself](https://github.com/rust-lang/cargo/issues/new)!
