### ISSUE TITLE
Command-line flags not recognized

### ISSUE THREAD

**Issue by pylaligand** [alexcrichton/cargo-vendor#27]
I ran `cargo install cargo-vendor` and then:
```sh
$ cargo -h vendor
error: Invalid arguments.

Usage:
    cargo <command> [<args>...]
    cargo [options]
```
and
```sh
$ cargo vendor -h
error: could not find `Cargo.lock`, must be run in a directory with Cargo.lock or use the `--sync` option

To learn more, run the command again with --verbose.
```

Am I holding it wrong? How do I print out the help - and then later actually use flags?

**Comment by raphlinus** [comment]
I can repro when I do `cargo install cargo-vendor`. In addition, `~/.cargo/bin/cargo-vendor vendor -h` has the same behavior. However, when I build from master, I don't see the behavior (it prints out help as expected). I haven't debugged further, but figured I'd update with that.

**Comment by pylaligand** [comment]
The master branch has https://github.com/alexcrichton/cargo-vendor/commit/8498de2582bdf0bb038cf5a78d525a39902c8ede which is related to flag parsing, maybe that commit is not available in the published version?

**Comment by pylaligand** [comment]
Yep, the crate was last published 19 days ago and the commit was made 4 days ago.

**Comment by alexcrichton** [comment]
I believe this is fixed on master now, so closing, thanks for the report though!
