### ISSUE TITLE
There should be tests for actually testing it against real cargo environment

### ISSUE THREAD

**Issue by upsuper** [alexcrichton/cargo-vendor#28]
Breakage like #27 (which suspiciously introduced by 1f73237) is pretty painful when people find their updated cargo-vendor doesn't work.

I think it would be helpful if there could be some tests in CI to test the common usage of cargo vendor, so that we can catch that kind of significant issues as soon as possible.

**Comment by alexcrichton** [comment]
Agreed! I just never got around to adding such tests :(
