### ISSUE TITLE
Does this support vendoring git dependencies?

### ISSUE THREAD

**Issue by bennofs** [alexcrichton/cargo-vendor#30]
It looks like this tool only vendors packages that are fetched from the `crates.io` registry. Would it be possible to vendor dependencies that are directly fetched from git repositories as well?

**Comment by alexcrichton** [comment]
Not currently, no. Support first needs to be added to Cargo and then support can be added here.

**Comment by djg** [comment]
I'm trying to get my code into gecko and it uses git dependencies for things that aren't on crates.io (eg. mio-more).  Is it just engineering work to allow cargo vendor to download git repos, or are there other reasons?

**Comment by bennofs** [comment]
@djg there is https://github.com/rust-lang/cargo/pull/3992 and https://github.com/alexcrichton/cargo-vendor/pull/42

**Comment by BenTheElder** [comment]
Was this fixed in #42? (it looks like it)

**Comment by alexcrichton** [comment]
Indeed!
