### ISSUE TITLE
Updating existing vendored crate

### ISSUE THREAD

**Issue by nipunn1313** [alexcrichton/cargo-vendor#33]
In our setup, when we want to upgrade an existing dependency we
1) Run the upgrade (eg futures 0.1.3 => 0.1.13) (get a new Cargo.lock file with the deps)
2) `rm -r vendor/`
3) Run `cargo vendor`

Ideally, it would be possible to eliminate step 2. Currently if `vendor/futures/.cargo-checksum.json` exists, it won't overwrite it. It would be nice if cargo vendor would verify if the crate is the right version.

This issue only comes up if `--explicit-version` is not set. If explicit version is set, then
`vendor/futures-0.1.3/.cargo-checksum.json` would be separate from
`vendor/futures-0.1.13/.cargo-checksum.json`

**Comment by alexcrichton** [comment]
Ah yes I believe this is similar to https://github.com/alexcrichton/cargo-vendor/issues/23

I'll look into trying to improve this interface soon.
