### ISSUE TITLE
Drop old versions from vendor/

### ISSUE THREAD

**Issue by nipunn1313** [alexcrichton/cargo-vendor#36]
Hey, I tried some of the new changes in 0.1.9 today and they're working great.

One request would be a mechanism to remove old versions as they aren't used. It's understandable that we wouldn't want this on-by-default in case there is one vendor directory being shared between different crates or workspaces.

However, in a one-workspace environment, there isn't a great way to do this short of `rm -r vendor/ ; cargo vendor`, which works but feels a bit strong of a hammer for the task.

**Comment by alexcrichton** [comment]
Yeah so originally `cargo-vendor` was supposed to work a little differently, but nowadays I don't think the original conception makes sense. With the ability to pass multiple manifests via a bunch of `-s` flags I think it makes sense for `cargo vendor` to totally own the `vendor` directory and actually by default delete all of it.

Basically I'm thinking:

* By default, `cargo vendor` is the equivalent of `rm -rf vendor; cargo vendor`
* There's an option, `--no-delete-vendor`, or something like that to avoid the previous `rm -rf`

How's that sound?

**Comment by nipunn1313** [comment]
That seems ok to me. Removes the optimization of skipping unchanged crates,
but that's probably fine.

We currently overlay some Bazel BUILD files in the dirs, but we can recover
them with a fancy git checkout command, so this will work for us.

Thanks
--Nipunn

**Comment by alexcrichton** [comment]
Ok, I've opted to just delete folders that look like they've got a `Cargo.toml` in there and are as a result managed by `cargo-vendor`, it should leave other folders/files intact.
