### ISSUE TITLE
Please document how to install a prebuild binary

### ISSUE THREAD

**Issue by whimboo** [alexcrichton/cargo-vendor#41]
As the docs say, there is also a way to install the prebuild binaries as can be found here:
https://github.com/alexcrichton/cargo-vendor/releases

But not sure which command or options are necessary. Also simply copying the binary into `.cargo/bin` does not work, because `cargo install --list` will not list it.

Thanks.

**Comment by alexcrichton** [comment]
Hm copying the binary into `.cargo/bin` not working is unexpected! Are you sure it's executable inside that directory? And this is `$HOME/.cargo/bin`, right?

In theory the instructions would be (a) un-tar and (b) copy to `$HOME/.cargo/bin`, but if that's not working that sounds bad!

**Comment by whimboo** [comment]
So executing the binary works, but cargo itself doesn't know about it. I assume it's happening because of the missing registry entry in `.cargo/.crates.toml`, and maybe other places.

**Comment by alexcrichton** [comment]
Cargo should search `$HOME/.cargo/bin` [by default](https://github.com/rust-lang/cargo/blob/aab5c348aa396070bb22f6be2de94caf6ecd5162/src/bin/cargo.rs#L388-L394), it shouldn't need to be in `.crates.toml` in theory. Are you sure this is placed in `$HOME/.cargo/bin` and `$HOME/.cargo` is the value of `CARGO_HOME` you're using?

**Comment by whimboo** [comment]
Sorry for replying that late, but I missed your response until now.

Maybe that was a problem in our bootstrap script at that time. When I had to run the command which uses `cargo-vendor` again a couple of days ago it was working all fine. 

Lets just close this issue for now, and if I see it again and have more data I might want to reopen again.
