### ISSUE TITLE
don't display configuration instructions if already configured

### ISSUE THREAD

**Issue by globau** [alexcrichton/cargo-vendor#43]
if .cargo/config is already correctly configured, cargo-vendor shouldn't display instructions stating that it needs to be configured.

**Comment by alexcrichton** [comment]
👍 

This'll probably be done by [adding a clause here](https://github.com/alexcrichton/cargo-vendor/blob/536b52eb8117bd6d4bd8d717c3aa0f20d62569c2/src/main.rs#L140-L151) and likely [reloading configuration to not remove `source`](https://github.com/alexcrichton/cargo-vendor/blob/536b52eb8117bd6d4bd8d717c3aa0f20d62569c2/src/main.rs#L39-L50) and probing for a few keys.

**Comment by alexcrichton** [comment]
This crate is now included natively in Cargo as of https://github.com/rust-lang/cargo/pull/6869 and today's nightly Rust. I'm closing all issues in this repository before I archive the repository, but if you're still interested in seeing this issue fixed then please feel free to file an issue with [Cargo itself](https://github.com/rust-lang/cargo/issues/new)!
