### ISSUE TITLE
Provide tarball with vendored sources

### ISSUE THREAD

**Issue by bachp** [alexcrichton/cargo-vendor#50]
With https://github.com/rust-lang/cargo/pull/2857 being merged `cargo vendor` seems like a useful tool to  implement a fetch task for build systems like [Nix](https://nixos.org/nix/) or [Yocto](https://www.yoctoproject.org/).

However there seems to be a bootstraping issues. In order to fetch the dependencies of `cargo vendor` you already need `cargo vendor`.

One elegant solution would be to provide a source tarball that containes the `vendored-sources` directory of a release. This way `cargo vendor` could be built without needing the dependency fetch state and thus avoiding the bootstrap problem.

**Comment by alexcrichton** [comment]
Seems plausible to me! I probably won't have time to do this, but would welcome a patch for CI to do so
