### ISSUE TITLE
missing `registry =` line

### ISSUE THREAD

**Issue by zimbatm** [alexcrichton/cargo-vendor#55]
In the README the output looks like:

    [source.crates-io]
    registry = 'https://github.com/rust-lang/crates.io-index'
    replace-with = 'vendored-sources'

    [source.vendored-sources]
    directory = '/home/alex/code/cargo-vendor/vendor'

When running cargo vendor the `registry =` line is missing. What are the implications?

**Comment by zimbatm** [comment]
This is part of my investigation to package rust properly as part of nixpkgs: https://github.com/NixOS/nixpkgs/pull/30088

**Comment by alexcrichton** [comment]
Ah this was historically required but no longer required! Probably just need to update the README
