### ISSUE TITLE
error: no source URL specified for `source.https://github.com/jwilm/libfontconfig`, need either `registry` or `local-registry` defined

### ISSUE THREAD

**Issue by zimbatm** [alexcrichton/cargo-vendor#56]
How to reproduce:
```
$ git clone https://github.com/jwilm/alacritty.git
$ cd alacritty
$ mkdir .cargo
$ cargo vendor > .cargo/config # tweak accordingly
    Updating registry `https://github.com/rust-lang/crates.io-index`
    Updating git repository `https://github.com/jwilm/rust-fontconfig`
    Updating git repository `https://github.com/jwilm/libfontconfig`
 Downloading magenta v0.1.1
 Downloading regex v0.2.2
[snip]
$ rm -rf ~/.cargo
$ cargo build
error: no source URL specified for `source.https://github.com/jwilm/libfontconfig`, need either `registry` or `local-registry` defined 
```

top-level Cargo.toml depends on ./fonts, which depends on https://github.com/jwilm/rust-fontconfig which depends on https://github.com/jwilm/libfontconfig

Both git dependencies are in vendor/servo-fontconfig and vendor/servo-fontconfig-sys respectively.
I suspect that the `~/.cargo/git` cache is necessary to establish the map from the git repo to the package name?

**Comment by alexcrichton** [comment]
I think this may just be a feature that's implemented on beta but not on stable yet? I got the same failure on stable but it built correctly on beta.

**Comment by zimbatm** [comment]
That's good news! Do you know how long it will be until beta goes to stable?

**Comment by alexcrichton** [comment]
You can find that info here: https://forge.rust-lang.org/

Rust 1.22 stable will release on Thu Nov 23 2017.

**Comment by zimbatm** [comment]
@alexcrichton is it possible that your `~/.cargo` wasn't flushed for you?

I am now using rust 1.22, cargo 1.22 and cargo-vendor 1.13 and getting the same issue.

This is part of the rust packaging effort in nix where every step is sandboxed. First we are getting all of the dependencies with cargo-vendor, store them into the /nix/store, then use that to compile the package. So both steps are separated and the `~/.cargo` folder is lost in between.

**Comment by zimbatm** [comment]
The generated `.cargo/config` looks like this:
```
[source.crates-io]
replace-with = "vendored-sources"

[source."https://github.com/jwilm/libfontconfig"]
git = "https://github.com/jwilm/libfontconfig"
branch = "updated-2017-10-8"
replace-with = "vendored-sources"

[source."https://github.com/jwilm/rust-fontconfig"]
git = "https://github.com/jwilm/rust-fontconfig"
branch = "updated-2017-10-8"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "/nix/store/sj64n9740rb10c1444y1x01i63f6d565-alacritty-unstable-2017-11-20-vendor"
```

**Comment by alexcrichton** [comment]
Are you sure you're using an up-to-date Cargo? Cargo 1.22 doesn't actually exist...

**Comment by zimbatm** [comment]
Sorry, it should have been 0.22.0. I see that a new release have been published 10 hours ago, I will give it a try.

**Comment by zimbatm** [comment]
Would you be open to have a longer chat on rust packaging with potentially nix integration? It would be nice if I could nail the implementation to make it the best experience possible.

**Comment by alexcrichton** [comment]
Certainly yeah! It may be good roping in the rest of the Cargo team to the discussion as well (as it's likely highly related to build system integration)

**Comment by zimbatm** [comment]
Cool! What is the best way to organize that? I think on our end, @Mic92 would also be interested in participating in the discussion.

**Comment by Mic92** [comment]
In addition to basing builds on Cargo, we also now have a different promising approach
that increases also sharing of libraries between different projects and also allow to specify dependency on system libraries and non-cargo depedencies in a central place: https://github.com/NixOS/nixpkgs/pull/31150

**Comment by alexcrichton** [comment]
It may be best to start out with a discussion on internals perhaps to see which Cargo team members are interested in participating?

**Comment by zimbatm** [comment]
Ok thanks. Cargo 0.23.0 fixes this ticket's issue.
