### ISSUE TITLE
[replace] sections

### ISSUE THREAD

**Issue by ljli** [alexcrichton/cargo-vendor#59]
Using cargo vendor on packages with [replace] sections seems to fail with a warning about duplicate sources. Specifically I had that problem with rustup: NixOS/nixpkgs/issues/30742. I could work around that (rust-lang-nursery/rustup.rs#1276), but there should probably be a general solution.

I made a naive attempt to solve this by only adding a pkg to the `ids` map, if it is not replaced. cargo vendor succeeds then, but cargo build says with the printed .cargo/config:
```
   error: checksum for `mio v0.6.11` could not be calculated, but a checksum is listed in the existing lock file

this could be indicative of a few possible situations:

    * the source `registry https://github.com/rust-lang/crates.io-index` supports checksums,

      but was replaced with one that doesn't
    * the lock file is corrupt

unable to verify that `mio v0.6.11` is the same as when the lockfile was generated
```

**Comment by alexcrichton** [comment]
Yeah I think to handle replace/patch this'll need some intrusive management of the lock file, or at least it's not clear immediately how it'd be handled :(

**Comment by alexcrichton** [comment]
This is a very old bug at this point and I think it's fixed with `[patch]` which has replaced `[replace]`, so I'm going to close this.
