### ISSUE TITLE
A workspace with patch section functions for cargo build but not for cargo vendor

### ISSUE THREAD

**Issue by rtsuk** [alexcrichton/cargo-vendor#60]
Sample here: https://github.com/rtsuk/vendoring

```
twonky:vendoring robtsuk$ cargo build
   Compiling bitflags v1.0.0
   Compiling libc v0.2.33
   Compiling rand v0.3.17
   Compiling enhunt v0.1.0 (file:///Users/robtsuk/projects/rust_stuff/vendoring/enhunt)
   Compiling frobulate v0.1.0 (file:///Users/robtsuk/projects/rust_stuff/vendoring/frobulate)
    Finished dev [unoptimized + debuginfo] target(s) in 2.68 secs

twonky:vendoring robtsuk$ cargo vendor
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: failed to sync

Caused by:
  failed to load pkg lockfile

Caused by:
  no matching package named `enhunt` found (required by `frobulate`)
location searched: registry https://github.com/rust-lang/crates.io-index
version required: ^0.1.0
```

**Comment by alexcrichton** [comment]
Looks like this was fixed recently, presumably from updating `cargo` as a dependency I think. In any case I'm gonna close but I'll tag a new version soon!

**Comment by rtsuk** [comment]
What are the steps I can take to confirm that this is working now? Just download, building and running ../../target/release/cargo vendor shows it still being a problem.

**Comment by alexcrichton** [comment]
Hm if you used `cargo` as an executable, did you rebuild Cargo or cargo-vendor?

**Comment by rtsuk** [comment]
Just cargo.

**Comment by alexcrichton** [comment]
Ah ok, I think you'll need to rebuild cargo-vendor as it's own personal dependency on Cargo was what was updated, and the most recent version of cargo-vendor I think is required

**Comment by rtsuk** [comment]
Yep, cargo install of both led to a working configuration. Now I just need to figure out how to undo that. :)
