### ISSUE TITLE
Vendoring crate from git repo produces invalid .cargo-checksum.json

### ISSUE THREAD

**Issue by djg** [alexcrichton/cargo-vendor#61]
I'm trying to vendor tokio-uds into Gecko since the git repo has fixes my code needs. cargo-vendor version 0.1.12 produces `"package": null` in the jSON, which causes Gecko build to fail:
```
 0:01.99 error: failed to load source for a dependency on `log`
 0:01.99 
 0:01.99 Caused by:
 0:01.99   Unable to update registry https://github.com/rust-lang/crates.io-index
 0:01.99 
 0:01.99 Caused by:
 0:01.99   failed to update replaced source `registry https://github.com/rust-lang/crates.io-index`
 0:01.99 
 0:01.99 Caused by:
 0:01.99   failed to decode `.cargo-checksum.json` of tokio-uds v0.1.6
 0:02.00 
 0:02.00 Caused by:
 0:02.00   invalid type: unit value, expected a string at line 1 column 674
```

.cargo-checksum.json:
```json
{"files":{".travis.yml":"931def7b1510d5bcefff1addb0c804de4b20dd57d6d71062aa5c31f5383dfb64","Cargo.toml":"c8e69d8e264381e1a3bbd0bb540c86f02db13f9f22ea1adeba1645241965a407","LICENSE-APACHE":"a60eea817514531668d7e00765731449fe14d059d3249e0bc93b36de45f759f2","LICENSE-MIT":"69036b033e4bb951821964dbc3d9b1efe6913a6e36d9c1f206de4035a1a85cc4","README.md":"d99405dcf91b78024df7460186680c5334524232338cd9ddce0d39639958694a","src/frame.rs":"bf35e7134ce40679ca8125dbb008871db54af50450b6b389284d505e110bd0bd","src/lib.rs":"04b1cbf5a0fa2f62a0e1f9441caaed877e008eb43cc7b3fa15ac52e7da37904a","src/ucred.rs":"c60465ebe515eefea6de9a09e5ae67538ed28509a5c6553ef67541dca6a80bb2"},"package":null}
```

**Comment by alexcrichton** [comment]
Hm what version of Cargo was the Gecko build using? I think a relatively new Cargo is required to work with vendoring git repos

**Comment by djg** [comment]
I believe it's using the system installed version of cargo, which is reportedly:

```
$ cargo --version
cargo 0.22.0 (3423351a5 2017-10-06)
```

**Comment by alexcrichton** [comment]
Maybe try a nightly version of Cargo? See if that has the same error message?

**Comment by alexcrichton** [comment]
This crate is now included natively in Cargo as of https://github.com/rust-lang/cargo/pull/6869 and today's nightly Rust. I'm closing all issues in this repository before I archive the repository, but if you're still interested in seeing this issue fixed then please feel free to file an issue with [Cargo itself](https://github.com/rust-lang/cargo/issues/new)!
