### ISSUE TITLE
The source release tar.gz configures vendored deps, but not .cargo/config

### ISSUE THREAD

**Issue by nipunn1313** [alexcrichton/cargo-vendor#63]
For example `cargo-vendor-src-0.1.13.tar.gz` from the releases page.

Inside the tar, we have all the source to `cargo-vendor` itself as well as vendored dependencies. However, if you fetch this tar and do a `cargo build`, it does not appear to use the vendored deps because `.cargo/config` is not set in that directory.

Looking at the .travis.yml, I think the pre-deploy step needs to set the .cargo/config.

**Comment by alexcrichton** [comment]
This crate is now included natively in Cargo as of https://github.com/rust-lang/cargo/pull/6869 and today's nightly Rust. I'm closing all issues in this repository before I archive the repository, but if you're still interested in seeing this issue fixed then please feel free to file an issue with [Cargo itself](https://github.com/rust-lang/cargo/issues/new)!
