### ISSUE TITLE
Attempting to vendor a git replacement for a crates.io crate results in error

### ISSUE THREAD

**Issue by staktrace** [alexcrichton/cargo-vendor#64]
What I'm trying to do is run cargo-vendor in Gecko, after adding some git crate replacements. Specifically, I'm taking the replacements indicated at https://github.com/servo/webrender/pull/2128/commits/57d9165d10bd66f00af81a157efdb39aeb1a9496#diff-80398c5faae3c069e4e6aa2ed11b28c0R13 and putting them into toolkit/library/rust/Cargo.toml and toolkit/library/gtest/rust/Cargo.toml. Running `cargo update` on these works fine. However when I go to run `mach vendor rust`, it produces this:

```
Caused by:
  found duplicate version of package `serde v1.0.8` vendored from two sources:

	source 1: https://github.com/gankro/serde?branch=deserialize_from_enums3#01f8e598
	source 2: registry https://github.com/rust-lang/crates.io-index
```

Is this use-case intended to work? When I look in the Cargo.lock files, the sections for serde and serde_derive look like this:

```
[[package]]                                                                      
name = "serde"                                                                   
version = "1.0.8"                                                                
source = "git+https://github.com/gankro/serde?branch=deserialize_from_enums3#01f8e598705093a1f42e558099c6dcdfd96b9111"
dependencies = [                                                                 
 "serde_derive 1.0.8 (git+https://github.com/gankro/serde?branch=deserialize_from_enums3)",
]                                                                                
                                                                                 
[[package]]                                                                      
name = "serde"                                                                   
version = "1.0.8"                                                                
source = "registry+https://github.com/rust-lang/crates.io-index"                 
replace = "serde 1.0.8 (git+https://github.com/gankro/serde?branch=deserialize_from_enums3)"
                                                                                 
[[package]]                                                                      
name = "serde_derive"                                                            
version = "1.0.8"                                                                
source = "git+https://github.com/gankro/serde?branch=deserialize_from_enums3#01f8e598705093a1f42e558099c6dcdfd96b9111"
dependencies = [                                                                 
 "quote 0.3.15 (registry+https://github.com/rust-lang/crates.io-index)",         
 "serde_derive_internals 0.17.0 (git+https://github.com/gankro/serde?branch=deserialize_from_enums3)",
 "syn 0.11.11 (registry+https://github.com/rust-lang/crates.io-index)",          
]                                                                                
                                                                                 
[[package]]                                                                      
name = "serde_derive"                                                            
version = "1.0.8"                                                                
source = "registry+https://github.com/rust-lang/crates.io-index"                 
replace = "serde_derive 1.0.8 (git+https://github.com/gankro/serde?branch=deserialize_from_enums3)"
```

and I'm assuming that this is normal, but that cargo-vendor doesn't know how to deal with it? I'm running cargo-vendor v0.1.13, latest from crates.io

**Comment by staktrace** [comment]
I wrote a small patch to skip over replaced packages and that seems to work. Still testing, will make a PR if it checks out.

**Comment by staktrace** [comment]
The patch did what I wanted, but it uncovered other issues.

@alexcrichton I could use some help here. The patch I had in mind is at https://github.com/staktrace/cargo-vendor/commit/fbc53e8d919bca9484cb090aebd1fd25be4d0ba5 - does this seem like a reasonable change to you?

What happens when I use this (even on a vanilla mozilla-central), is that it removes the vendoring of libudev-sys from `third_party/rust`. This is actually good, because it fixes the issue described at https://bugzilla.mozilla.org/show_bug.cgi?id=1388843#c31 ("we don't actually need libudev-sys itself. We have our own copy but "mach vendor rust" doesn't respect the [replace] directives in the Cargo.toml files."). However, cargo fails to build the rust code because it's not smart enough to realize that that it doesn't need the vendored copy of libudev-sys. Try push with that failure is at https://treeherder.mozilla.org/#/jobs?repo=try&revision=699f74086a88a188ee63219d805634b85bb4778c

Since I don't really care about libudev-sys one way or the other, I modified my patch to keep libudev-sys vendored, the updated version is at https://github.com/staktrace/cargo-vendor/commit/f4ff0c59373f7e10a8d470576f216535510346ae - this solves the libudev-sys problem by keeping the unnecessarily vendored copy to satisfy cargo. However, there is still a build failure (see https://treeherder.mozilla.org/#/jobs?repo=try&revision=c2c60efed2dcc583ab291c305a59a7cc38355e36) due to checksums. The error produced by cargo now is:

```
INFO -  error: checksum for `serde v1.0.8` could not be calculated, but a checksum is listed in the existing lock file
INFO -  this could be indicative of a few possible situations:
INFO -      * the source `registry https://github.com/rust-lang/crates.io-index` supports checksums,
INFO -        but was replaced with one that doesn't
INFO -      * the lock file is corrupt
INFO -  unable to verify that `serde v1.0.8` is the same as when the lockfile was generated
```

It seems like the first situation described above (the crates.io source was replaced by a git source) is in fact what's happening here, and I'm not sure why this is being treated as an error. It seems like cargo should have enough information to know this is the case and build anyway.

Do you know what I can do about this?

**Comment by alexcrichton** [comment]
@staktrace that seems like a plausible patch to me! I haven't spent any cycles yet thinking about how `cargo vendor` interacts with `[replace]` though so before merging I'd want to think a little more carefully. In general though I'd definitely expect that `cargo vendor` is broken at least in some respects with `[replace]` active.

Want to send a PR with some tests perhaps and we can maybe go from there?

**Comment by Gankro** [comment]
lmk if there's anything I can do to help

**Comment by staktrace** [comment]
@alexcrichton I can make the PR but I feel like it would be better to get a set of patches locally that get the use case fully working first. I'm not yet at that stage, and I think it might be because of bugs in cargo itself. However I'll try and make a reduced test case in a standalone repo so we can figure out what the expected behaviour is.

**Comment by alexcrichton** [comment]
Ok sounds good to me!

**Comment by staktrace** [comment]
@alexcrichton I made a repo at https://github.com/staktrace/cargo-vendor-replace with the setup that I'm having trouble with. I have a dummy crate ("crate1") which has a dependency - vendoring that works fine. Then I [replace]'d that dependency with a git branch and vendored it (using a patched version of https://github.com/staktrace/cargo-vendor/commit/fbc53e8d919bca9484cb090aebd1fd25be4d0ba5) and now it fails to build with cargo.

If you are attempt to repro locally please note you'll need to edit the absolute path in crate1/.cargo/config

**Comment by alexcrichton** [comment]
Ok I think I may see what's going on. If I'm right, this is one of the main reasons that `[replace]` was, well, replaced. When using `[replace]` then the original crate must still exist and be resolved, but the replacement for `[replace]`, `[patch]`, does not have this restriction.

This means that when you run `cargo build` it actually needs to find two crates, both the crates.io version and the vendored git version. Unfortunately though `cargo vendor` isn't producing a source tree that actually has this. Only the git version is vendored and the crates.io version isn't actually vendored. When Cargo sees this it spits out a misleading and uninformative error message unfortunately.

I'm not sure if it's possible to actually get `[replace]` working with one vendor directory in that sense. I *do* think that it would work to vendor the git repo in one dir and the crates.io repos in another dir, however, which presumably `cargo vendor` could produce automatically?

**Comment by staktrace** [comment]
Thanks! I was completely unaware of `[patch]` and indeed that looks like it should solve my problem. I'll close this issue once I've verified it all works.

**Comment by staktrace** [comment]
Confirmed that using `[patch]` does exactly what I need and allows us to vendor the modified serde with a minimum of fuss. Thanks again!

**Comment by alexcrichton** [comment]
Nice! Glad it works!
