### ISSUE TITLE
Could you please provide 32bit version? NixOS fails to provide 32 bit FireFox without it.

### ISSUE THREAD

**Issue by avodonosov** [alexcrichton/cargo-vendor#65]
Related NixOS issues:
https://github.com/NixOS/nixpkgs/issues/32074
https://github.com/NixOS/nixpkgs/issues/32655#issuecomment-351894718

The cargo-vendor NixOS package:
https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/rust/cargo-vendor.nix

**Comment by alexcrichton** [comment]
Thanks for the report! For now though this repo will just host 64-bit binaries, for 32-bit you'll need to build/mirror locally.

**Comment by avodonosov** [comment]
MIrror?  Is there a place to mirror from? Do the 32bit binaries exist somewhere?

**Comment by alexcrichton** [comment]
No, they don't exist, that was just something you'd have to do.

**Comment by avodonosov** [comment]
Thank you. Are difficulties possoble whej building 32 bits.
