### ISSUE TITLE
Add a way to get configuration info programmatically

### ISSUE THREAD

**Issue by sid0** [alexcrichton/cargo-vendor#66]
I'm trying to incorporate cargo-vendor into the preparation (network-accessible) phase of one of our builds. This works great if the only dependencies I'm pulling in are from crates.io. But some of the projects I'm trying to build (like rls) have Git dependencies.

The problem is that the cargo vendor configuration becomes specific to that version at that point, since it'll refer to e.g. `branch = "master"` or `rev = "foobar"`. It would be great if the configuration could also be output to a file on the side so that my build step can grab it for later use.

Thanks!

**Comment by alexcrichton** [comment]
Sounds plausible to me! I'm not sure I fully understand though what change this'd be? Right now `cargo vendor` prints out (for the rls repo):

```
[source.crates-io]
replace-with = "vendored-sources"

[source."https://github.com/rust-lang/cargo"]
git = "https://github.com/rust-lang/cargo"
rev = "6a8eb71f6"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "/home/alex/code/rls/vendor"
```

What part are you thinking should be in a separate file?

**Comment by sid0** [comment]
All of it, I think -- the idea is that a simple enough build process can use the contents verbatim as the cargo config.

**Comment by alexcrichton** [comment]
Ah ok, so right now it's printed to stdout while everything else is printed to stderr, would `tee` work in this case for extracting the contents?

**Comment by sid0** [comment]
Is this guaranteed to remain stable? If so, that sounds reasonable.

**Comment by alexcrichton** [comment]
Indeed! I think the idea is that you do:

```
cargo vendor > .cargo/config
```

or something like that

**Comment by sid0** [comment]
Cool! Could this be documented? That would be amazing, thanks.
