### ISSUE TITLE
CRLF being replaced by LF causes checksum issues on OSX

### ISSUE THREAD

**Issue by michaeleiselsc** [alexcrichton/cargo-vendor#68]
Hi, I'm not sure if this is right place to raise this issue, but when I run `cargo vendor` and it downloads a bunch of source files, the downloaded files use CRLF instead of LF. Then git automatically replaces them with LF for OSX people, and so when people pull the files, they find that the checksums don't match. Is there some way to fix this issue? Thanks

**Comment by alexcrichton** [comment]
Thanks for the report! The primary way to handle this is to use a gitattributes file telling git to ignore the crlf settings and treat the files as binary, and then it shouldn't bother with the files internally. If that works though this should be added to the README!

**Comment by michaeleiselsc** [comment]
Yes, that does appear to work, thanks!

**Comment by alexcrichton** [comment]
I'm gonna close this since this works with crlf handling in git
