### ISSUE TITLE
Support for vendoring on a single platform

### ISSUE THREAD

**Issue by nipunn1313** [alexcrichton/cargo-vendor#70]
Hi,

At Dropbox, we have a desktop client use case which requires `cargo-vendor` to vendor deps across all platforms (cargo-vendor is great here)

We also have a server use case in which we'd prefer to vendor deps just for linux (currently, we end up pulling in some windows-specific deps, some of which are quite large (eg 50MB of .a files here https://github.com/retep998/winapi-rs/tree/0.3/i686/lib)

Currently `cargo-vendor` will pull in optional windows dependencies even if we don't need them. I believe this happens in `resolve_ws` here https://github.com/rust-lang/cargo/blob/master/src/cargo/ops/resolve.rs#L16

It would be great to have an option to exclude windows-specific dependencies for cases where we know we're only building for linux.

**Comment by alexcrichton** [comment]
Certainly a feature I'd like to implement! Supporting this will be pretty difficult though, unfortunately. Cargo currently requires that the lock file is platform-independent, meaning that the lock file (and generating the lock file) always has to locate all crates for all possible platforms. This means that if you were to remove the winapi folder, for example, then a lock file would no longer be correctly generated.

There's a tracking issue for this at https://github.com/rust-lang/cargo/issues/5133 which is a possible way to pass a flag to Cargo and say "please generate a minimal lock file", and with that we can safely delete all the dependencies for other platforms.

**Comment by alexcrichton** [comment]
This crate is now included natively in Cargo as of https://github.com/rust-lang/cargo/pull/6869 and today's nightly Rust. I'm closing all issues in this repository before I archive the repository, but if you're still interested in seeing this issue fixed then please feel free to file an issue with [Cargo itself](https://github.com/rust-lang/cargo/issues/new)!
