### ISSUE TITLE
cargo-installable?

### ISSUE THREAD

**Issue by jesskfullwood** [alexcrichton/cargo-vendor#72]
Hi, thanks for the really useful crate. I installed it frome `crates.io` with `cargo install cargo-vendor` and it seemed to work fine, but the instructions suggest you should install directly from github. Is this instruction outdated or is there some good reason not to install from `crates.io`? A note would be helpful.

**Comment by alexcrichton** [comment]
Oh oops that's a holdover from a long time ago! Nowadays `cargo install cargo-vendor` is A-OK
