### ISSUE TITLE
the result between two cargo-vendor runs changed in few weeks

### ISSUE THREAD

**Issue by psumbera** [alexcrichton/cargo-vendor#73]
Not sure whether this is real problem.

My use case is to download all dependencies for e.g. cargo or rust build. After that I create GNU tar archive where I reset time to 1970 and force owner to root. This way I'm able to create unique archive with particular sha256 check sum. I can recreate the same archive even on different computer. 

But I have find out the data can differ after few weeks or days. Which is causing problems. It seems that some crater versions were updated in between.

But not sure how it's possible. Original cargo or rust version lists still the same version dependencies.

To be more specific I'm preparing integration of Rust into Solaris where our build system is using sha256 check sum, it caches these archives and it needs to be reproducible.
(example: https://github.com/oracle/solaris-userland/blob/master/components/desktop/firefox/Makefile)

**Comment by alexcrichton** [comment]
Are you using a lock file between runs of cargo-vendor?

**Comment by psumbera** [comment]
No. I start new workspace totally from scratch.

**Comment by alexcrichton** [comment]
Ah ok, I believe that's the issue then! A lock file is required to guarantee that you get the same set of dependencies every time, so you'll want to check in and persist `Cargo.lock`

**Comment by psumbera** [comment]
Ok. It makes sense. I will try to archive also `Cargo.lock` file. But not sure why it's not included directly in cargo-0.26.0 archive. To me 'cargo' is binary not library?! Thanks!

**Comment by psumbera** [comment]
I see that the issue was already discussed here:
https://github.com/rust-lang/cargo/commit/5c9665f41c6b4d3b99d3b9f8b48a286f5f154692
