### ISSUE TITLE
winapi

### ISSUE THREAD

**Issue by Thomspoon** [alexcrichton/cargo-vendor#74]
Hello,

I recently used cargo-vendor to create a snapshot of my program on Linux for an identical PC. I noticed that it captured the following crates:

- winapi
- winapi-0.2.8
- winapi-build
- winapi-i686-pc-windows-gnu
- winapi-x86_64-pc-windows-gnu

If these crates are specific to Windows, why were they included in a Linux build?

**Comment by nipunn1313** [comment]
Hiya

Check out #70 - I think it's covering a broader topic including this one.
We ran into the same issue over on our project. Looks like it's on their roadmap, but not a simple fix.

I'd propose we merge this report into #70

**Comment by alexcrichton** [comment]
Indeed I believe this is the same as https://github.com/alexcrichton/cargo-vendor/issues/70!
