### ISSUE TITLE
Symlinks only contain path when using a git branch on Windows

### ISSUE THREAD

**Issue by hcs64** [alexcrichton/cargo-vendor#77]
With the following in Cargo.toml:

```Cargo.toml
[dependencies]
serde_derive = { git = "https://github.com/servo/serde", branch = "deserialize_from_enums8" }
```

I get files like vendor/serde_derive/LICENSE-APACHE that just contain "../LICENSE-APACHE". If I remove the `branch` I get the proper contents. These files are in Git as symlinks. I expect this is probably an [issue with libgit2 on Windows](https://github.com/libgit2/libgit2/issues/4107), but there is clearly some way this is being avoided when `branch` isn't being used. Is it possible to have that same behavior with `branch`?

**Comment by alexcrichton** [comment]
This does indeed sound bad, thanks for the report! This does sort of sound like a Windows issue though and it may be the case that the branch contents are different? Or maybe the way symlinks are handled when switching branches is different? I'm not entirely sure unfortunately :(

**Comment by alexcrichton** [comment]
This crate is now included natively in Cargo as of https://github.com/rust-lang/cargo/pull/6869 and today's nightly Rust. I'm closing all issues in this repository before I archive the repository, but if you're still interested in seeing this issue fixed then please feel free to file an issue with [Cargo itself](https://github.com/rust-lang/cargo/issues/new)!
