### ISSUE TITLE
Pregenerated files in vendored sources

### ISSUE THREAD

**Issue by akru** [alexcrichton/cargo-vendor#89]
Motivation:
* https://github.com/briansmith/ring/pull/680
* https://github.com/paritytech/parity-ethereum/issues/8612

I have a build troubles in maintained rust package for `nixpkgs`. As you can see [here](https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/rust/fetchcargo.nix), `cargo-vendor` is used in nix build system to build Rust applications.

The seed of current problem is using pregenerated asm files in `ring` library, library check for building in git repo, but `cargo-vendor` cleanup `.git` folders. The reason of this issue is find a way to success vendorizing of `ring` library.

@briansmith can you help me? Can you explain your vision of this problem?

**Comment by akru** [comment]
You can reproduce fail sequence locally without nix:

```bash
$ git clone https://github.com/paritytech/parity-ethereum -b v1.11.7 && cd parity-ethereum
$ cargo vendor >> .cargo/config
$ cargo build
111

**Comment by alexcrichton** [comment]
@akru Ah ok! I think the bug here is that the *git repository* isn't compatible with `cargo vendor`, which I think is expected from how *ring* builds? If you vendor crates.io though, it should work?

**Comment by briansmith** [comment]
> @akru Ah ok! I think the bug here is that the git repository isn't compatible with cargo vendor, which I think is expected from how ring builds? If you vendor crates.io though, it should work?

Ah, yes. You have to cargo vendor the crates.io crate, not your clone of the git repo.
